# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-19 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='site_url',
            field=models.CharField(max_length=400, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='site',
            unique_together=set([]),
        ),
    ]
